local:
  url: http://localhost:8084/ui/#login
  username: superadmin
  password: erebus

prod:
  url: https://reportportal.epam.com/ui/#login
  username: pungvun4uk
  password: Welcome!123

api:
  url: https://reportportal.epam.com/api/v1/
  username: pungvun4uk
  password: Welcome!123

